version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: onepercentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    command: sh -c "python manage.py migrate && python manage.py create_superuser && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB_NAME=onepercentdb
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=postgres
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432

  frontend:
    build:
      context: ./frontend  # Path to your Vue.js project directory
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
